scrape_configs:
  - job_name: 'bot'

    metrics_path: '/metrics'

    scrape_interval: 5s

    static_configs:
      - targets: ['host.docker.internal:8091']
        labels:
          application: 'bot'

  - job_name: 'scrapper'

    metrics_path: '/metrics'

    scrape_interval: 5s

    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'scrapper'

