app:
  telegram-token: ${TOKEN}
  retry-config:
    back-off-type: exponential
    attempts: 1
    status-codes:
      - 500
      - 502
      - 503
      - 504
    min-delay: 100
    jitter: 0.5
  time-rate-config:
    capacity: 20
    tokens: 20
    duration: 6000000
  topic:
    name: bot_updates
    partitions: 5
    replicas: 2
  dead-letter-topic:
    name: updates_dl
    partitions: 5
    replicas: 3

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
