/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables;

import edu.java.scrapper.domain.jooq.DefaultSchema;
import edu.java.scrapper.domain.jooq.Keys;
import edu.java.scrapper.domain.jooq.tables.records.ChatToLinkConnectionRecord;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ChatToLinkConnection extends TableImpl<ChatToLinkConnectionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CHAT_TO_LINK_CONNECTION</code>
     */
    public static final ChatToLinkConnection CHAT_TO_LINK_CONNECTION = new ChatToLinkConnection();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<ChatToLinkConnectionRecord> getRecordType() {
        return ChatToLinkConnectionRecord.class;
    }

    /**
     * The column <code>CHAT_TO_LINK_CONNECTION.CHAT_ID</code>.
     */
    public final TableField<ChatToLinkConnectionRecord, Long> CHAT_ID =
        createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CHAT_TO_LINK_CONNECTION.LINK_ID</code>.
     */
    public final TableField<ChatToLinkConnectionRecord, Long> LINK_ID =
        createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private ChatToLinkConnection(Name alias, Table<ChatToLinkConnectionRecord> aliased) {
        this(alias, aliased, null);
    }

    private ChatToLinkConnection(Name alias, Table<ChatToLinkConnectionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>CHAT_TO_LINK_CONNECTION</code> table reference
     */
    public ChatToLinkConnection(String alias) {
        this(DSL.name(alias), CHAT_TO_LINK_CONNECTION);
    }

    /**
     * Create an aliased <code>CHAT_TO_LINK_CONNECTION</code> table reference
     */
    public ChatToLinkConnection(Name alias) {
        this(alias, CHAT_TO_LINK_CONNECTION);
    }

    /**
     * Create a <code>CHAT_TO_LINK_CONNECTION</code> table reference
     */
    public ChatToLinkConnection() {
        this(DSL.name("CHAT_TO_LINK_CONNECTION"), null);
    }

    public <O extends Record> ChatToLinkConnection(Table<O> child, ForeignKey<O, ChatToLinkConnectionRecord> key) {
        super(child, key, CHAT_TO_LINK_CONNECTION);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<ChatToLinkConnectionRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_12;
    }

    @Override
    @NotNull
    public List<ForeignKey<ChatToLinkConnectionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_121, Keys.CONSTRAINT_1213);
    }

    private transient Chat _chat;
    private transient Link _link;

    /**
     * Get the implicit join path to the <code>PUBLIC.CHAT</code> table.
     */
    public Chat chat() {
        if (_chat == null) {
            _chat = new Chat(this, Keys.CONSTRAINT_121);
        }

        return _chat;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null) {
            _link = new Link(this, Keys.CONSTRAINT_1213);
        }

        return _link;
    }

    @Override
    @NotNull
    public ChatToLinkConnection as(String alias) {
        return new ChatToLinkConnection(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public ChatToLinkConnection as(Name alias) {
        return new ChatToLinkConnection(alias, this);
    }

    @Override
    @NotNull
    public ChatToLinkConnection as(Table<?> alias) {
        return new ChatToLinkConnection(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatToLinkConnection rename(String name) {
        return new ChatToLinkConnection(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatToLinkConnection rename(Name name) {
        return new ChatToLinkConnection(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatToLinkConnection rename(Table<?> name) {
        return new ChatToLinkConnection(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
